<a href="https://colab.research.google.com/github/RijaBarhin/Data-Analytics-using-python-project/blob/main/Day3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

ARRAYS

1d array

In [ ]:
import numpy as np

marks = np.array([90, 85, 78, 92])

print(marks)

[90 85 78 92]


2d array

In [ ]:
import numpy as np

marks = np.array([
    [90, 85, 78],
    [92, 88, 95]
])

print(marks)

[[90 85 78]
 [92 88 95]]


3d array

In [ ]:
import numpy as np

marks = np.array([
    [
        [90, 85, 78],
        [92, 88, 95]
    ],
    [
        [80, 75, 70],
        [85, 90, 88]
    ]
])

print(marks)

[[[90 85 78]
  [92 88 95]]

 [[80 75 70]
  [85 90 88]]]


CREATING ARRAYS USING FUNCTION

np.zeros()

In [ ]:
import numpy as np

arr = np.zeros((2,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


np.ones()

In [ ]:
import numpy as np

arr = np.ones((2,2))
print(arr)

[[1. 1.]
 [1. 1.]]


np.arange()

In [ ]:
import numpy as np

arr = np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


np.linspace()

In [ ]:
import numpy as np

arr = np.linspace(1,10,5)
print(arr)

[ 1.    3.25  5.5   7.75 10.  ]


np.random.rand()

In [ ]:
import numpy as np

arr = np.random.rand(3)
print(arr)

[0.51381601 0.49920545 0.15907024]


np.eye()

In [ ]:
import numpy as np

matrix = np.eye(3)
print(matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Array Indexing Program

In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print(arr[0])
print(arr[2])
print(arr[4])

10
30
50


Array Slicing Program

In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print(arr[1:4])

[20 30 40]


PRACTICE:

Student Score Program:

In [ ]:
scores = [78, 85, 92, 67, 88]

total = sum(scores)
average = total / len(scores)
highest = max(scores)
lowest = min(scores)

print("Student Scores:", scores)
print("Total Marks:", total)
print("Average Marks:", average)
print("Highest Mark:", highest)
print("Lowest Mark:", lowest)

Student Scores: [78, 85, 92, 67, 88]
Total Marks: 410
Average Marks: 82.0
Highest Mark: 92
Lowest Mark: 67


Sales Array Calculations

In [ ]:
sales = [1200, 1500, 1800, 1000, 2000]

total_sales = sum(sales)
average_sales = total_sales / len(sales)
highest_sales = max(sales)
lowest_sales = min(sales)

print("Sales:", sales)
print("Total Sales:", total_sales)
print("Average Sales:", average_sales)
print("Highest Sales:", highest_sales)
print("Lowest Sales:", lowest_sales)

Sales: [1200, 1500, 1800, 1000, 2000]
Total Sales: 7500
Average Sales: 1500.0
Highest Sales: 2000
Lowest Sales: 1000


Attendance calculator

In [ ]:
def calculate_attendance(total, attended):
    percentage = (attended / total) * 100
    return percentage

try:
    total_classes = int(input("Enter Total Classes: "))
    attended_classes = int(input("Enter Attended Classes: "))

    attendance = calculate_attendance(total_classes, attended_classes)

    print("Attendance Percentage =", attendance, "%")

except ValueError:
    print("Invalid Input! Enter numbers only.")

except ZeroDivisionError:
    print("Total Classes cannot be zero.")

Enter Total Classes: 5
Enter Attended Classes: 4
Attendance Percentage = 80.0 %


Average calculator

In [ ]:
def calculate_average(a, b, c):
    return (a + b + c) / 3

try:
    num1 = float(input("Enter First Number: "))
    num2 = float(input("Enter Second Number: "))
    num3 = float(input("Enter Third Number: "))

    avg = calculate_average(num1, num2, num3)

    print("Average =", avg)

except ValueError:
    print("Invalid Input! Enter numbers only.")

Enter First Number: 7
Enter Second Number: 5
Enter Third Number: 6
Average = 6.0
