<a href="https://colab.research.google.com/github/RijaBarhin/Data-Analytics-using-python-project/blob/main/DAY4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

RESHAPE

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

new_arr = arr.reshape(2, 3)

print(new_arr)

[[1 2 3]
 [4 5 6]]


TRANSPOSE

In [ ]:
import numpy as np

a = np.arange(1, 7)

b = a.reshape(2, 3)
print(b)

c = b.T
print(c)

d = a.reshape(-1, 2)
print(d)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[1 2]
 [3 4]
 [5 6]]


Mean value

In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

average = np.mean(arr)

print("Average =", average)

Average = 30.0


Median value

In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40,50])

print("Median =", np.median(arr))

Median = 30.0


Standard deviation

In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print("Standard Deviation =", np.std(arr))

Standard Deviation = 14.142135623730951


PRACTICE:

Employee Salary Analysis

In [ ]:
import numpy as np

employees = ["Ravi", "Priya", "Kumar", "Divya", "Arun"]

salary = np.array([25000, 30000, 28000, 35000, 32000])

# Total Salary
print("Total Salary:", np.sum(salary))

# Average Salary
print("Average Salary:", np.mean(salary))

# Highest Salary
print("Highest Salary:", np.max(salary))

# Lowest Salary
print("Lowest Salary:", np.min(salary))

# Highest Paid Employee
best_index = np.argmax(salary)
print("Highest Paid Employee:", employees[best_index])

# Employee Salary Report
print("\nEmployee Salary Report")
for i in range(len(employees)):
    print(employees[i], "-", salary[i])

Total Salary: 150000
Average Salary: 30000.0
Highest Salary: 35000
Lowest Salary: 25000
Highest Paid Employee: Divya

Employee Salary Report
Ravi - 25000
Priya - 30000
Kumar - 28000
Divya - 35000
Arun - 32000
